import React from "react";

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "@style";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Props {
  children: React.ReactNode;
  params: {
    locale: "ar" | "en";
  };
}
export default async function RootLayout(props: Props) {
  const { children, params } = props;
  let messages;
  try {
    messages = (await import(`../../../messages/${params.locale}.json`))
      .default;
  } catch (error) {}

  if (!messages) return notFound();
  return (
    <html
      lang={params.locale}
      dir={params.locale === "en" ? "ltr" : "rtl"}
      data-layout-dir={params.locale === "en" ? "ltr" : "rtl"}
      data-preloader="disable"
    >
      <body dir={params.locale === "en" ? "ltr" : "rtl"}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <main>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
